"""add model selection and pipeline config columns

Revision ID: afbaeef965c2
Revises: c864f2d3917b
Create Date: 2026-04-12 21:08:28.428557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afbaeef965c2'
down_revision: Union[str, Sequence[str], None] = 'c864f2d3917b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persons', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('pipeline_config', sa.Text(), nullable=False, server_default='{}'))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yolo_model', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('pipeline_params', sa.Text(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('pipeline_params')
        batch_op.drop_column('yolo_model')

    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_column('pipeline_config')
        batch_op.drop_column('persons')

    # ### end Alembic commands ###
