"""initial schema

Revision ID: c864f2d3917b
Revises: 
Create Date: 2026-04-10 11:26:24.157910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c864f2d3917b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('annotated_filename', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('video_id', sa.Text(), nullable=False),
    sa.Column('total_unique', sa.Integer(), nullable=False),
    sa.Column('total_analyzed', sa.Integer(), nullable=False),
    sa.Column('foot_traffic', sa.Text(), nullable=False),
    sa.Column('age_distribution', sa.Text(), nullable=False),
    sa.Column('gender_distribution', sa.Text(), nullable=False),
    sa.Column('processing_time_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_results')
    op.drop_table('videos')
    # ### end Alembic commands ###
